version: "3"

services:
  ws:
    image: simanno/ws:2.0
    volumes:
     - $PWD/conf/ws:/opt/ft/ws/conf
     - $PWD/data/images:/data/images
     - $PWD/data/db:/data/db
    ports:
      - "5000:5000"

  web:
    image: simanno/web:2.0
    ports:
      - "8181:4200"