version: "3"

services:
  ws:
    image: faisalthaheem/simanno-be:latest
    volumes:
    #The CMD in docker file expects this file at this location
     - $PWD/be/imanno.yaml:/app/imanno.yaml
    #The default imanno.yaml file expects this directory to be mounted at /app/images.
     - $PWD/be/sample-images:/app/sample-images
    #The default imanno.yaml file expects the database at this location.
     - $PWD/be/db/sample.db:/app/db/sample.db
    ports:
      - "8000:8000"

  web:
    image: faisalthaheem/simanno-fe:latest
    ports:
      - "8181:80"