version: "3"

services:
  ws:
    image: faisalthaheem/simanno-be:dev
    volumes:
     - $PWD/sample-conf/be:/simanno/be/conf
     - $PWD/sample-images:/images
     - $PWD/sample-db:/dbs
    ports:
      - "5000:5000"

  web:
    image: faisalthaheem/simanno-fe:dev
    ports:
      - "8181:80"
